Added a header to get rid of this: editmesh_loop.c:305: warning: implicit declaration of function `backdrawview3d'
I also removed the config.h stuff from this file, since were not using autoconf

Kent


git-svn-id: https://svn.blender.org/svnroot/bf-blender/trunk@3439 954f8c5b-7b00-dc11-b283-0030488c597c